### PR TITLE
Improved comm library usage. Non-blocking channel selecting.

### PR DESCRIPTION
**Pull request by sfisol**

### CODE REVIEW

**Comment by szagi3891** [comment]
Przykładowe uruchomienie i wyłączenie :

<EventLoop>         : miohttp 6 -> set mode WaitingForServerResponse, reregister                                                    : Error | Hup, timer clear
<EventLoop>         : count hasmapy after insert 3
^[[15~^[[15~^[[15~^[[15~^[[15~^[[15~<EventLoop>         : miohttp 1 -> ready, Hup (is server = false)
<EventLoop>         : hashmap after decrement 2
<EventLoop>         : miohttp 1 -> ready, event hup, Hup
<EventLoop>         : miohttp 2 -> ready, Hup (is server = false)
<EventLoop>         : hashmap after decrement 1
<EventLoop>         : miohttp 2 -> ready, event hup, Hup
<EventLoop>         : miohttp 6 -> ready, Hup (is server = false)
<EventLoop>         : hashmap after decrement 0
<EventLoop>         : miohttp 6 -> ready, event hup, Hup
^C<unnamed>           : Termination signal catched.

gszeliga@dev4:~/workspace/testhttp$ <main>              : Shutting down!
<Static worker #3>  : rx_api_request channel error: Deadlock
<Static worker #2>  : rx_api_request channel error: Deadlock
<Static worker #1>  : rx_api_request channel error: Deadlock
<Static worker #0>  : rx_api_request channel error: Deadlock
<Static worker #4>  : rx_api_request channel error: Deadlock
<main>              : Waiting for workers to end...
<main>              : Bye.

**Comment by szagi3891** [comment]
z new-feature też :

```
<EventLoop>         : count hasmapy after insert 3
<EventLoop>         : miohttp 12 -> ready, Readable (is server = false)
<EventLoop>         : hashmap after decrement 2
<EventLoop>         : Sending request through channel 1
<EventLoop>         : Sending request through channel 2
<EventLoop>         : miohttp 12 -> set mode WaitingForServerResponse, reregister: Error | Hup, timer clear
<EventLoop>         : count hasmapy after insert 3
<EventLoop>         : hashmap after decrement 2
<EventLoop>         : miohttp 13 -> timeout_trigger ok
^C<unnamed>           : Termination signal catched.
<main>              : Shutting down!

gszeliga@dev4:~/workspace/testhttp$ <Static worker #3>  : rx_api_request channel error: Deadlock
<Static worker #2>  : rx_api_request channel error: Deadlock
<Static worker #1>  : rx_api_request channel error: Deadlock
<Static worker #0>  : rx_api_request channel error: Deadlock
<Static worker #4>  : rx_api_request channel error: Deadlock
<main>              : Waiting for workers to end...
<main>              : Bye.

```

**Comment by sfisol** [comment]
A może cargo update ? :-)

**Comment by szagi3891** [comment]
Te błędy pochodzą ze świeżego zaciągniętego repozytorium.

**Pull request merged**
